get-convex/convex-helpers

- convex/lib/withUser.ts
Removed a duplicate mutationWithuser function that inserted a message into the database (seemed to be an example/boilerplate function), which was causing errors
> Remove erroneous mutationWithUser default function

- convex/_generated/api.d.ts
- convex/lib/rowLevelSecurity.ts
add middleware helper for implementing row-level-security.
as far as i can tell, the typescript types work for all ways of defining queries and mutations.
we can discuss on this PR or on the blog post draft or in person.
> add RowLevelSecurity middleware

- convex/lib/rowLevelSecurity.ts
noticed that when you call `db.query("table").filter(...).unique()` with row-level-security and there are no results, we call the row-level-security `read` predicate on `null`, which doesn't match the typescript types and isn't expected. Instead, we should only call the predicate on non-null documents.
> [RLS] fix error on unique() that returns null

- convex/lib/rowLevelSecurity.ts
- package-lock.json
- package.json
fix small type errors in RLS caused by slightly changed types in convex 0.16.0. Otherwise I don't think any of the breaking changes affect convex-helpers
> upgrade convex to 0.16.0

- src/hooks/useServerSession.ts
I just noticed that the session middleware now requires you pass {} as an arg if the session ID was the only arg.
useSessionQuery spreads the args. Any reason mutation shouldn't?
> allow empty arg for useSessionMutation too

- packages/convex-helpers/server/customFunctions.ts
I'm not sure how to test this exactly in this repo, but I tested it in mine and it works.
In my file with custom functions I can now do:
```ts
export const queryFoo = customQuery(
baseQuery,
customCtx(async (ctx) => {
return {
/// some customization....
};
})
);
export type QueryFooCtx = CustomCtx<typeof query>;
```
> Add CustomCtx type helper

- convex/relationshipsExample.ts
- convex/schema.ts
- packages/convex-helpers/index.ts
- packages/convex-helpers/package.json
- packages/convex-helpers/publish.sh
- packages/convex-helpers/server/relationships.ts
I found myself wanting `asyncMap` to provide an index in `asyncTransform` props.
In my case I was updating an order column on a list of records and found it convenient to have an index while mapping over them and building a return. For instance: 
```javascript
// Update the order of all courseLessons to keep
await asyncMap(courseLessons, (cm, index) => {
return ctx.db.patch(cm._id, { order: index + 1 });
});
```
So, this PR adds an index to the asyncTransform params on asyncMap! Might be a rare use case, but I thought I'd put it out there anyhow.
```javascript
/**
* asyncMap returns the results of applying an async function over an list.
*
* @param list - Iterable object of items, e.g. an Array, Set, Object.keys
* @param asyncTransform
* @returns
*/
export async function …
```
> Add index to async map asyncTransform params

- README.md
- convex/_generated/api.d.ts
- convex/http.ts
- packages/convex-helpers/README.md
- packages/convex-helpers/package-lock.json
- packages/convex-helpers/package.json
- packages/convex-helpers/server/hono.ts
- src/App.tsx
- src/components/HonoExample.tsx
Allows using hono without copy-paste. It is now parameterized by `ActionCtx` when declaring it, instead of importing from a generated file.
> Move Hono into `convex-helpers` npm package

- src/components/Counter.mock.test.tsx
- src/fakeConvexClient/fakeConvexClient.js
- vite.config.mts
We have several `.test.ts` files that aren't actually vitest tests, one of which does not actually run (`zod.test`).
This excludes them. This also fixes the fake ConvexReactClient + mock test.
> Make `npm run test` pass

- Justfile
- README.md
- backendHarness.js
- convex/_generated/api.d.ts
- convex/example.test.ts
- convex/testingFunctions.ts
- package-lock.json
- package.json
- packages/convex-helpers/package.json
- packages/convex-helpers/testing.ts
- vite.config.mts
Adds `ConvexTestingHelper` to the `convex-helpers` npm package + a simple example of running tests with a local backend.
> Add support for tests against a local backend

- convex/validatorsExample.ts
- packages/convex-helpers/validators.ts
Adds convenience validators for when you don't mind some targeted incorrectness, esp. while you do migrations
Can be part of a post on pragmatic migration dev tips. Saves you from turning on & off schemaValidation.
Flow to add a field:
1. Add `myField: pretendRequired(v.string()),` and code that sets & uses myField as if it exists[ and a migration to set it].
2. Deploy & change the data in the dashboard [or run the migration]
3. Some time later, take off the `pretendRequired` wrapper and deploy.
Improves over the following in that you don't have to sprinkle `if` statements everywhere:
1. Add `myField: v.optional(v.string())` and code that handles it not being there[ and a migration to set it].
2. Same as above
3. Update the code to assume it's there (take out all the `if(!doc.newField) …
> pretend validators

- README.md
- convex/_generated/api.d.ts
- convex/retriesExample.ts
- packages/convex-helpers/README.md
- packages/convex-helpers/package.json
- packages/convex-helpers/server/customFunctions.ts
- packages/convex-helpers/server/retries.ts
Adds the retry helpers from https://github.com/JamesCowling/convex-action-retrier
Changes the API to instead of exposing a mutation to run, expose a type-safe function that schedules both, whether you're in an action or mutation. The only risk with this is if you call it from an action and the scheduler succeeds on the first but fails the retrier on the second, and the called action fails, which seems exceedingly unlikely.
> Add Retries helpers and example

- package-lock.json
- packages/convex-helpers/package-lock.json
- packages/convex-helpers/package.json
- packages/convex-helpers/publish.sh
- packages/convex-helpers/react/sessions.ts
Support SSR with the SessionProvider by supplying a default value on the first pass client and server-side, and skipping queries that use that value. opt-in via `ssrFriendly`
> Sessions with SSR

- packages/convex-helpers/react/sessions.ts
Changes behavior for SSR:
- The value will not be persisted until there's a valid ID.
- Queries will skip until there's a valid ID
- Mutations and actions will await a promise for the first valid ID.
Breaking change for non-SSR (types only):
- The type for `useSessionId` now is `SessionId | undefined`. The value will not be undefined except if `ssrFriendly` is used and it's the first render. It's safe to use `sessionId!` if you aren't setting `ssrFriendly`. After considering a different API for SSR, this seemed like the most composable option. h/t to @conradkoh for feedback
> sessionIdPromise instead of throwing

- packages/convex-helpers/publish.sh
- packages/convex-helpers/server/customFunctions.ts
While I was respecting all the types, I wasn't actually forwarding the return value validator to the original function wrapper.
> Actually propagate return value validator in customFunctions

- packages/convex-helpers/react/cache/hooks.ts
- packages/convex-helpers/react/sessions.ts
- packages/convex-helpers/server/customFunctions.test.ts
- packages/convex-helpers/server/index.ts
- packages/convex-helpers/server/migrations.ts
- packages/convex-helpers/server/relationships.ts
- packages/convex-helpers/server/retries.ts
- packages/convex-helpers/server/rowLevelSecurity.ts
- packages/convex-helpers/server/zod.ts
- packages/convex-helpers/tsconfig.json
- packages/convex-helpers/validators.ts
gets rid of the tests/ directory in favor of inlining tests. requires some hacks for getting tests to load their own functions.
----
> Move tests into packages/convex-helpers

- .github/workflows/test.yml
- package-lock.json
- package.json
- packages/convex-helpers/package-lock.json
- packages/convex-helpers/package.json
- packages/convex-helpers/react/cache/provider.tsx
- renovate.json
The cache provider was making a new registry on every invocation, which happened when auth providers would refresh every time they logged in. This would result in multiple registries being created, which isn't necessarily the worst thing (not sure why they weren't garbage collected better though), except newer registries wouldn't get a callback on `onUpdate` from the `watchQuery` if there was already results, so they would be stale until a change came down. Also, all caches would be lost on page transitions. 
Now we memoize the registry, and also trigger the setter the first time if there's already a result. Which also helps if the result had been pre-warmed by a useQuery not using the cache helper.
I also fixed the issue in #147 by inlining the lookup. Good to know that ES2020 isn't as …
> Handle multiple cache registry instantiations and initial cache hits

- package-lock.json
- packages/convex-helpers/generate-exports.mjs
- packages/convex-helpers/package.json
- packages/convex-helpers/react.ts
- packages/convex-helpers/server.ts
- publish.sh
Add wildcard exports to package to enable VSCode autocomplete for the library.
In addition to the explicit enumeration, so that we can still use arethetypeswrong.
involves moving *.index.ts files into *.ts files
----
> Wildcard-export

- package-lock.json
- packages/convex-helpers/README.md
- packages/convex-helpers/package.json
- packages/convex-helpers/react/cache.ts
- packages/convex-helpers/react/cache/hooks.ts
- packages/convex-helpers/react/cache/provider.tsx
- publish.sh
- src/App.tsx
- src/components/CacheExample.tsx
Haven't tested it yet, but this would allow us to leverage cached `useQueries` without `useEffect`, enabling better server-side isomorphic opportunities. 
It essentially reduces the registry to a ref counter on subscriptions, vs. also being the source of truth for the value of the query
----
> Cached use queries

- packages/convex-helpers/package.json
Previously, the binary was only included in the top-level directory and not in the package that is shipped.
----
> Add CLI binary within package that we ship

- packages/convex-helpers/package.json
We only copy the `dist` package when publishing, so all paths need to be relative to the `/dist` folder.
----
> Move bin from `./dist/bin.cjs` -> `./bin.cjs`

- packages/convex-helpers/server/hono.ts
Implements a fix allowing the Hono 404 route to trigger, preventing an error from being returned.
[discord](https://discord.com/channels/1019350475847499849/1283924028012363877) 
----
> Refactor HttpRouterWithHono to handle empty handlersAndRoutes array

- convex/triggersExample.ts
- packages/convex-helpers/README.md
- packages/convex-helpers/server/triggers.test.ts
- packages/convex-helpers/server/triggers.ts
Instead of wrapping the whole custom function and needing to use its nuanced interface to extend, let's just get them using `customCtx` from day one. My prettier config breaks it into multiple lines anyways, so it wouldn't have been a one-liner either way.
I have prettier changes that I omitted for this PR. Not sure if I'm running something different or if you aren't running it
----
> Change triggers API to work alongside `customCtx`

- packages/convex-helpers/server/relationships.ts
fixes `getAll` so it works with stateful `db` implementations, like `WrapWriter` as used by `wrapDatabaseWriter` for RLS.
----
> fix getAll to bind db

- packages/convex-helpers/server/customFunctions.test.ts
- packages/convex-helpers/server/rateLimit.test.ts
- packages/convex-helpers/server/rowLevelSecurity.test.ts
- packages/convex-helpers/server/validators.test.ts
- packages/convex-helpers/server/zod.test.ts
Clean up warnings of the form
```
Promise returned by `expect(actual).rejects.toThrow(expected)` was not awaited. Vitest currently auto-awaits hanging assertions at the end of the test, but this will cause the test to fail in Vitest 3. Please remember to await the assertion.
```
----
> await expected failures in tests

- packages/convex-helpers/server/hono.ts
whoops I changed the types in https://github.com/get-convex/convex-backend/commit/064d9d387b9d0848d4992874cd03792b9ed91646 (because `httpAction(...)` should not be callable as if it were a plain js function).
Didn't realize the type was used by HonoWithConvex.
We can fix it like this PR does, by changing the types of HonoWithConvex to use PublicHttpAction.
An alternative might be for `getRoutes` to directly return the function which has the line numbers that you want.
----
> fix types with new convex version

- packages/convex-helpers/server/filter.test.ts
- packages/convex-helpers/server/filter.ts
the docstring of `filter` says that you can apply `filter` to queries that already have an `order`. Let's make it true.
I don't know why I need the cast `query as unknown as OrderedQuery<QueryTableInfo<Q>>`, but it looks safe and nothing is changing at runtime, only types are changing in this PR.
Added a test that previously failed.
----
> fix filter types to support order

- package-lock.json
- packages/convex-helpers/package.json
- packages/convex-helpers/server/pagination.ts
as implemented here: https://github.com/get-convex/convex-backend/blob/54d629f272c60a88c0784aefabfce11108687468/npm-packages/local-store/shared/pagination.ts#L127
this is a straightforward refactor that gives applications access to the lower-level stream, before page boundaries have been selected.
----
> Refactor `streamQuery` out of `getPage`

- packages/convex-helpers/server/pagination.test.ts
- packages/convex-helpers/server/pagination.ts
there's a bug where `endCursor` is not used for the last page of pagination. What should happen is the last page grows to include everything up to endCursor, like every other page. But what was happening instead is it was being cut off at num-items.
----
> fix paginator endCursor when isDone

- packages/convex-helpers/cli/utils.ts
in the case of an error, we throw an Error with the result.stderr, but when we catch this error there are two problems:
1. we print a generic error message, discarding the stderr
2. we process.exit which means the finally block never gets called to clean up the temp file
----
> api-function-spec error handling

- src/hooks/useStableQuery.ts
It seems useStablePaginatedQuery is missing a loading case to not rerender the UI.
This PR add the missing case and ensures the UI is not rerendering while loading the first page. 
It's particularly visible when a paginated query is used with a `withSearchIndex` and a user is typing a text that does a paginated query. Without this check, the UI keeps rerendering every time the user types on a character on the keyboard.
----
> add missing case for paginated queries

- packages/convex-helpers/server/filter.ts
_Similar to [this PR I opened](https://github.com/get-convex/convex-backend/pull/59) in the convex-backend repo_
Makes the error message thrown by .unique() more useful. Now, the _id's of the first two documents returned by the unique() query are printed in the error message. This is very helpful to the user in identifying and resolving incorrect data.
The wording in the error message has been changed such that it is identical to the error thrown by `.unique()` from `convex-backend` (slightly confusing that the same error has different error messages based on where it's thrown from).
Feel free to change my wording in the error message - but in my opinion it should be clear that the document id's printed are not all the documents returned by the unique() query but just the first two. …
> improve .unique() error message

- packages/convex-helpers/browser.ts
As a future direction how about withArgs can return more full wrappers of various clients? If that works as a plan then it's fine to add more clients here and a type parameter for the client type in the future, but for now it's just the same interface!
> Allow ConvexHttpClient in withArgs

- README.md
- package-lock.json
- package.json
- packages/convex-helpers/README.md
- packages/convex-helpers/generate-exports.mjs
- packages/convex-helpers/package.json
- packages/convex-helpers/standardSchema.test.ts
- packages/convex-helpers/standardSchema.ts
not quite #558 but at least you can do something like 
```ts
import { toStandardSchema } from "convex-helpers/standardSchema";
const standardValidator = toStandardSchema(v.object({
name: v.string(),
age: v.number(),
}));
standardValidator["~standard"].validate({
name: "John",
age: 30,
});
```
---
> Add standard schema support

- packages/convex-helpers/server/zod.ts
- fix a typo in `packages/convex-helpers/server/zod.ts`
- `npm test` *(fails: vitest not found)*
> Fix misspelling in zod comment

- packages/convex-helpers/cli/utils.ts
- correct path in warning when temp file deletion fails
- `npm test` *(fails: vitest not found)*
> Fix temp file warning path

- convex/counter.ts
- package-lock.json
- packages/convex-helpers/CHANGELOG.md
- packages/convex-helpers/package.json
- packages/convex-helpers/react/cache.ts
- packages/convex-helpers/react/cache/hooks.ts
- packages/convex-helpers/server/pagination.test.ts
- packages/convex-helpers/server/stream.test.ts
- packages/convex-helpers/server/stream.ts
- src/components/CacheExample.tsx
Fixes #630
We were producing ranges to query that were like
a lt 2
a eq 2, b lt 3
a eq 2, b eq 3, c lt 4
...
but for descending iteration, we need these ranges to be reversed, which is important for ConcatStreams
----
> fix stream pagination for descending cursors

- packages/convex-helpers/cli/functions.test.ts
- packages/convex-helpers/cli/tsApiSpec.ts
Use type imports when generating tsApiSpec.
This syntax is supported in Typescript versions 3.8.0 and above which was released in February 2020.
----
> fix: add type annotations to imports in  tsApiSpec

- convex/testingFunctions.ts
- packages/convex-helpers/README.md
- packages/convex-helpers/server/customFunctions.test.ts
- packages/convex-helpers/server/customFunctions.ts
- packages/convex-helpers/server/zod.ts
Now you can specify extra parameters at the function definition site and use them in the customFunction builder
```ts
const myQueryBuilder = customQuery(query, {
args: {  },
input: async (ctx, args, { role }: { role: "admin" | "user" }) => {
const user = await getUser(ctx);
if (role === "admin" && user.role !== "admin") {
throw new Error("You are not an admin");
}
if (role === "user" && !user) {
throw new Error("You must be logged in to access this query");
}
return { ctx: { user }, args: {} };
}
});
const myAdminQuery = myQueryBuilder({
role: "admin",
args: { },
handler: async (ctx, args) => {
// ...
},
});
```
----
> Custom function allows extra params

- packages/convex-helpers/server/pagination.ts
- packages/convex-helpers/server/stream.test.ts
- packages/convex-helpers/server/stream.ts
> serde for undefined

- packages/convex-helpers/server/stream.ts
I'm creating Effect wrappers around Convex and ConvexHelpers, and while working on the stream helpers, I struggled a lot with TypeScript because I don't have access to the type of the internal `QueryStream` class. If it's ok to export it that would help me avoid having to do castings to `any` 😅.
(If not, that's fine)
----
> Export QueryStream

- packages/convex-helpers/react/sessions.test.ts
- packages/convex-helpers/react/sessions.ts
This PR makes it so that functions that have all of their args set to optional don't have to pass an empty object to the session query to fix type errors.
----
> fix: make all partial args result in optional arg
