- convex/README.md
- convex/_generated/api.d.ts
- convex/counter.ts
- convex/schema.ts
- package-lock.json
- package.json
- src/App.tsx
- src/components/Counter.injection.test.tsx
- src/components/Counter.mock.test.tsx
- src/components/Counter.test.tsx
- src/components/Counter.tsx
- src/mockClient/mockClient.d.ts
- src/mockClient/mockClient.js
- vite.config.ts
Adds a unit test example with the vitest framework and a mock convex client for testing queries, mutations, and actions
> Add unit test example

- src/hooks/useStableQuery.ts
Contains `useStableQuery` and `useStablePaginatedQuery` hooks detailed in upcoming Stack post
Feedback more than welcome!
> Add useStableQuery.ts

- convex/tsconfig.json
- package-lock.json
- package.json
- src/fakeConvexClient/fakeConvexClient.d.ts
- src/hooks/useStableQuery.ts
- src/main.tsx
* Updated the tsconfig.json with `npx convex codegen --init`
* Added a missing type dependency that meant the whole project failed to typecheck
* Updated some incorrect imports
> Make various fixes to convex helpers repo

- convex/lib/withSession.ts
I think this was just a bad copy paste, but I was throwing for the optional session when the session wasn't provided.
> Fix incorrect error in withOptionalSession

- README.md
- convex/_generated/api.d.ts
- convex/crudExample.ts
- packages/convex-helpers/README.md
- packages/convex-helpers/server/index.ts
- src/App.tsx
- src/components/CrudExample.tsx
Helpers to add Create Read Update and Delete functions for a table.
> CRUD Helpers

- packages/convex-helpers/react/sessions.ts
Hi, proposing a small quality-of-life improvement. Motivations:
- In my case: testing on iOS devices on my local network was failing, because crypto.randomUUID is not available when the protocol is not `https://` but `http://`. This change allows me to create session IDs with the CUID generator (which doesn't complain) instead
- Hypothetically: one might want or need a different format of session IDs, for some reason
> SessionProvider: allow session IDs from a supplied function

- package-lock.json
- package.json
- packages/convex-helpers/package-lock.json
- packages/convex-helpers/package.json
- tests/package-lock.json
- tests/package.json
Newer version of `convex-test` allows you to query on by_creation_time, which will be helpful.
----
> upgrade convex-test dep

- .vscode/convex.code-snippets
- packages/convex-helpers/react/cache/hooks.ts
- packages/convex-helpers/server/hono.ts
- packages/convex-helpers/server/migrations.ts
- packages/convex-helpers/server/pagination.ts
- packages/convex-helpers/server/rateLimit.ts
- packages/convex-helpers/tsconfig.json
Improving the tsconfig strictness so we don't cause type issues for developers importing this code
----
> Stricter tsconfig

- packages/convex-helpers/package.json
> Add `convex-helpers` command to `package.json`

- packages/convex-helpers/server/filter.ts
This pull request fixes minor typos in the documentation and adds missing quotation marks in code examples.
----
> Fix typos in documentation and add missing quotation marks

- packages/convex-helpers/server/triggers.test.ts
test the field denormalization trigger
----
> add a test of Triggers

- .github/workflows/test.yml
- package.json
- packages/convex-helpers/server/zod.ts
See https://discord.com/channels/1019350475847499849/1298976854316814336
----
> Fix zodBranded conversion to Convex validator

- package-lock.json
- packages/convex-helpers/cli/utils.ts
- packages/convex-helpers/package.json
> try using npx.cmd

- packages/convex-helpers/server/stream.test.ts
- packages/convex-helpers/server/stream.ts
Implement `.distinct` on streams which allows you to implement equivalents of `SELECT DISTINCT` and loose index scans efficiently.
for example, with this stream you can do a query like
```sql
SELECT * FROM tbl WHERE a = 0 AND b > 1 AND c > 2
```
with an index on [a, b, c]
Motivated by discord question: https://discord.com/channels/1019350475847499849/1350399034896158811/1350399034896158811
Depends on #488
----
> [streams] distinct queries

- convex/sessionsExample.ts
- packages/convex-helpers/react/sessions.ts
- src/components/SessionsExample.tsx
Is that what we want to name it? I'll publish an alpha now
> useSessionPaginatedQuery

- packages/convex-helpers/server/rateLimit.ts
This is causing a tsc build error.
----
> Update rateLimit.ts to export RateLimitArgsWithoutConfig

- packages/convex-helpers/README.md
- packages/convex-helpers/server/cors.ts
I run this in my own fork, but others may find it useful as well. Cors failures are silent and it's maddening lol.
~~Related: https://discord.com/channels/1019350475847499849/1374693671982600334/1374693671982600334~~
Update: they weren't using the cors helper 🤦‍♂️ so they didn't need debugging. But this is still worth considering.
> cors: add debug option

- packages/convex-helpers/react/sessions.ts
- fix example client class name in `sessions.ts`
- `npm test` *(fails: vitest not found)*
> Update react session example

- packages/convex-helpers/server/validators.test.ts
- packages/convex-helpers/validators.ts
fixes https://github.com/get-convex/convex-helpers/issues/622
> fix parse to handle union of literal types

- convex/counter.ts
- package-lock.json
- packages/convex-helpers/package.json
- packages/convex-helpers/react/cache.ts
- packages/convex-helpers/react/cache/hooks.ts
- packages/convex-helpers/server/validators.test.ts
- packages/convex-helpers/validators.ts
- src/components/CacheExample.tsx
Fixes #535 
In `convex-helpers@0.1.90-alpha.0` for validation
----
> cached usePaginatedQuery

- packages/convex-helpers/server/triggers.ts
Similar to #693 but going all in on objects over classes
----
> change trigger db wrapper from class to object
